version: '3.7'

services:
  shib-service-iis:
    image: uscdev/shib-service
    environment:
    - SERVER_NAME=${SERVER_NAME}
    - PROXY_URL=http://hello-iis:80/
    networks:
      proxy:
    secrets:
    - apache.crt
    - apache.key
    - sp-key.pem
    - sp-cert.pem
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
      labels:
      - com.df.notify=true
      - com.df.distribute=true
      - com.df.serviceDomain=hello-shib-iis.swarm-test.usc.edu
      - com.df.httpsOnly=true
      - com.df.port=443
      - com.df.sslVerifyNone=true
  hello-iis:
    image: microsoft/iis
    networks:
      - proxy
    deploy:
      replicas: 1
      labels:
        - com.df.notify=true
        - com.df.distribute=true
        - com.df.httpsOnly.1=true
        - com.df.serviceDomain.1=hello-world-iis.swarm-test.usc.edu
        - com.df.port.1=80
        - com.df.httpsOnly.2=true
        - com.df.serviceDomain.2=hello-iis.swarm-test.usc.edu
        - com.df.port.2=80
networks:
  proxy:
    external: true
secrets:
  apache.crt:
    external: true
  apache.key:
    external: true
  sp-key.pem:
    external: true
  sp-cert.pem:
    external: true