version: "3.7"

services:

  proxy:
    image: dockerflow/docker-flow-proxy:${TAG:-latest}
    ports:
    - 80:80
    - 443:443
    networks:
    - proxy
    - monitor
    environment:
      LISTENER_ADDRESS: swarm-listener
      MODE: swarm
      SSL_BIND_OPTIONS: no-sslv3 no-tlsv10 no-tlsv11 no-tls-tickets
      SSL_BIND_CIPHERS: ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-SHA384:ECDHE-RSA-AES256-SHA384:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA256
      CONNECTION_MODE: ${CONNECTION_MODE:-http-keep-alive}
    deploy:
      replicas: 3
    secrets:
      - cert-docker.usc.edu.pem
      - cert-emailchoice.usc.edu.pem
      - cert-workday-account-translator.usc.edu.pem
      - cert-itapps.usc.edu.pem
      - cert-device-registration.usc.edu.pem

  swarm-listener:
    image: dockerflow/docker-flow-swarm-listener
    networks:
    - monitor
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    environment:
    - DF_NOTIFY_CREATE_SERVICE_URL=http://prometheus:8080/v1/docker-flow-monitor/reconfigure,http://proxy:8080/v1/docker-flow-proxy/reconfigure
    - DF_NOTIFY_REMOVE_SERVICE_URL=http://prometheus:8080/v1/docker-flow-monitor/remove,http://proxy:8080/v1/docker-flow-proxy/remove
    deploy:
      labels:
      - com.df.alertName=memlimit
      - com.df.alertIf=@service_mem_limit:0.8
      - com.df.alertFor=30s
      placement:
        constraints: [node.role == manager]
      resources:
        reservations:
          memory: 10M
        limits:
          memory: 20M

networks:
  proxy:
    external: true
  monitor:
    external: true

secrets:
  cert-docker.usc.edu.pem:
    external: true
  cert-emailchoice.usc.edu.pem:
    external: true
  cert-workday-account-translator.usc.edu.pem:
    external: true
  cert-itapps.usc.edu.pem:
    external: true
  cert-device-registration.usc.edu.pem:
    external: true
